web/router.ex
defmodule Ap.Router do
  use Ap.Web, :router
  use Plug.ErrorHandler
  use Sentry.Plug

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers

  end

  pipeline :admin do
    plug :put_layout, {Ap.LayoutView, :admin}
    plug Ap.Plugs.Authenticate
  end


  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :default_assigns do
    plug Ap.Plugs.DefaultAssigns
  end

  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.EmailPreviewPlug
  end


  scope "/admin", Ap.Admin, as: :admin do
    pipe_through [:browser, :admin]

    get "/", DashboardController, :index
    resources "/users", UserController, only: [:edit, :update]

    # Blog posts
    get "/posts/drafts", PostController, :drafts
    get "/posts/published", PostController, :published
    resources "/posts", PostController
    resources "/post-categories", PostCategoryController

    # Products
    resources "/products", ProductController do
      resources "/images", ProductImageController, only: [:new, :create, :delete], as: :image
    end
    resources "/product-categories", ProductCategoryController

    resources "/pages", PageController

    # Image management from WYSIWYG editor
    post "/editor-image-upload", EditorImageUploadController, :create
    delete "/editor-image-upload", EditorImageUploadController, :delete

    resources "/support-messages", SupportMessageController, only: [:index, :show, :delete]
  end

  scope "/", Ap do
    pipe_through [:browser, :default_assigns]

    get "/", HomeController, :index
    resources "/sessions", SessionController, only: [:new, :create, :delete]

    # Newsletter
    get "/newsletter-subscribe", NewsletterSubscribeController, :index

    # Support requests
    resources "/contact", SupportMessageController, only: [:new, :create]

    # Blog
    get "/blog/categories/:slug", PostCategoryController, :show
    get "/blog/archives", PostArchiveController, :index
    resources "/blog", PostController, only: [:index, :show]

    # Static Pages
    get "/pages/:slug", PageController, :show

    # Products
    get "/preview/:slug", ProductPreviewController, :show
    get "/products/:slug", ProductCategoryController, :show
    get "/product/:slug", ProductController, :show
  end


  # Other scopes may use custom stacks.
  # scope "/api", Ap do
  #   pipe_through :api
  # end
end

web/models/product.ex
defmodule Ap.Product do
  use Ap.Web, :model
  import Ap.Utils.Sluggify
  import Ap.Utils.ManyToMany

  schema "products" do
    field :title, :string
    field :slug, :string
    field :page_title, :string
    field :content, :string
    field :vendor, :string
    field :demo_url, :string
    field :meta_description, :string
    field :extract, :string
    field :featured, :boolean
    field :base_price, :integer

    has_many :variants, Ap.Variant
    has_many :product_images, Ap.ProductImage
    many_to_many :product_categories, Ap.ProductCategory, join_through: "products_categories", on_delete: :delete_all

    timestamps()
  end

  def available_vendors do
    [
      "Gumroad": "gumroad",
      "Creative Market": "creativemarket",
      "Wrap Bootstrap": "wrapbootstrap"
    ]
  end

  def only_featured do
    from p in __MODULE__,
      where: p.featured == true,
      order_by: [desc: p.inserted_at]
  end

  def default_order(preloads \\ []) do
    from p in __MODULE__,
      order_by: [desc: p.inserted_at],
      preload: ^preloads
  end


  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :slug, :page_title, :content, :vendor, :demo_url, :meta_description, :extract, :featured, :base_price])
    |> cast_assoc(:variants, required: true)
    |> map_many_to_many_ids_to_records(:product_categories, Ap.ProductCategory)
    |> validate_required([:title, :page_title, :content, :vendor, :demo_url, :featured, :base_price])
    |> validate_length(:password, min: 6, max: 144)
    |> unique_constraint(:title)
    |> sluggify
    |> unique_constraint(:slug)
  end

  defp validate_presence_of_categories(changeset) do
    data = changeset.data
    changes = get_change(changeset, :product_categories)

    if data.product_categories == [] and !changes  do
      add_error(changeset, :product_categories, "can't be empty")
    else
      changeset
    end
  end

end

web/controllers/admin/product_controller.ex
defmodule Ap.Admin.ProductController do
  use Ap.Web, :controller

  alias Ap.Product
  alias Ap.ProductCategory

  plug :scrub_params, "product" when action in [:create, :update]

  def index(conn, params) do
    {products, kerosene} = Product |> Repo.paginate(params)
    render(conn, "index.html", products: products, kerosene: kerosene)
  end

  def new(conn, _params) do
    changeset = Product.changeset(%Product{ product_categories: [] })
    categories = Repo.all(ProductCategory.find_for_select)

    render(conn, "new.html", changeset: changeset, categories: categories)
  end

  def create(conn, %{"product" => product_params}) do
    changeset = Product.changeset(%Product{product_categories: []}, product_params)
    categories = Repo.all(ProductCategory.find_for_select)


    case Repo.insert(changeset) do
      {:ok, product} ->
        conn
        |> put_flash(:info, "Product created successfully.")
        |> redirect(to: admin_product_image_path(conn, :new, product))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset, categories: categories)
    end
  end

  def show(conn, %{"id" => id}) do
    product = Repo.get!(Product, id)
    |> Repo.preload([:variants, :product_categories])

    render(conn, "show.html", product: product)
  end

  def edit(conn, %{"id" => id}) do
    product = Repo.get!(Product, id)
    |> Repo.preload([:variants, :product_categories])

    categories = Repo.all(ProductCategory.find_for_select)

    changeset = Product.changeset(product)
    render(conn, "edit.html", product: product, categories: categories, changeset: changeset)
  end

  def update(conn, %{"id" => id, "product" => product_params}) do
    product = Repo.get!(Product, id)
    |> Repo.preload([:variants, :product_categories])

    categories = Repo.all(ProductCategory.find_for_select)
    changeset = Product.changeset(product, product_params)

    case Repo.update(changeset) do
      {:ok, product} ->
        conn
        |> put_flash(:info, "Product updated successfully.")
        |> redirect(to: admin_product_image_path(conn, :new, product))
      {:error, changeset} ->
        render(conn, "edit.html", product: product, categories: categories, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    product = Repo.get!(Product, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(product)

    conn
    |> put_flash(:info, "Product deleted successfully.")
    |> redirect(to: admin_product_path(conn, :index))
  end
end

web/controllers/product_controller.ex
defmodule Ap.ProductController do
  use Ap.Web, :controller

  alias Ap.Product
  alias Ap.Variant
  alias Ap.ProductImage

  def show(conn, %{"slug" => slug}) do
    product =
      Repo.get_by!(Product, slug: slug)
      |> Repo.preload([:product_categories])
      |> Repo.preload([variants: Variant.default_order, product_images: ProductImage.default_order])

    render(conn, "show.html", product: product)
  end
end

web/views/admin/product_view.ex
defmodule Ap.Admin.ProductView do
  use Ap.Web, :view
  import Kerosene.HTML

  alias Ap.Product
  alias Ap.Variant

  def link_to_add_variant do
    changeset = Product.changeset(%Product{variants: [%Variant{}]})
    form = Phoenix.HTML.FormData.to_form(changeset, [])
    fields = render_to_string(__MODULE__, "variant_fields.html", f: form)
    link "Add another variant", to: "#", "data-template": fields, id: "add-variant-btn", class: "btn btn-default"
  end

end

web/views/product_view.ex
defmodule Ap.ProductView do
  use Ap.Web, :view

  def featured_image_url([img | _]) do
    img.secure_url || img.url
  end

  def featured_image_url([]) do
    ""
  end

  def default_purchase_url([variant | _]), do: variant.purchase_url
  def default_purchase_url([]), do: ""

  def readable_price([variant | _]), do: readable_price(variant.price)
  def readable_price([]), do: ""
  def readable_price(num) do
    if num == 0 do
      "Free"
    else
      "$#{num}"
    end
  end

  def alternate_class_name(id, size, _direction) when rem(id, 2) == 0 do
    "col-md-#{size}"
  end

  def alternate_class_name(id, size, direction) do
    alt_size = 12 - size
    "col-md-#{size} col-md-#{direction}-#{alt_size}"
  end

  def render("meta.show.html", assigns) do
    product = assigns[:product]

    ~E{
    <title><%= product.page_title %> - Authentic Pixels</title>
    <meta name="description" content="<%= product.meta_description || product.extract %>" />
    }
  end

  def render("social_meta.show.html", assigns) do
    product = assigns[:product]
    conn = assigns.conn
    url = "https://www.authenticpixels.com" <> conn.request_path


    ~E{
    <meta property="og:url" content="<%= url %>">
    <meta property="og:title" content="<%= product.page_title %> - Authentic Pixels">
    <meta property="og:description" content="<%= product.meta_description || product.extract %>">
    <meta property="og:image" content="<%= featured_image_url(product.product_images) %>">

    <meta name="twitter:title" content="<%= product.page_title %> - Authentic Pixels">
    <meta name="twitter:description" content="<%= product.meta_description || product.extract %>">
    <meta name="twitter:image" content="<%= featured_image_url(product.product_images) %>">

    }
  end
end

web/templates/product/list.html.eex
<%= if @products != [] do %>
  <div class="products-container">
    <%=  for {product, id} <- Enum.with_index @products do %>
    <div class="product-item">
      <div class="row">
        <%= if product.product_images != [] do %>
          <div class="<%= alternate_class_name(id, 7, 'push') %>">
            <div class="product-image-container">
              <div class="browser">
                <div class="browser-header">
                  <span class="button"></span>
                  <span class="button"></span>
                  <span class="button"></span>
                </div>
                <a href="<%= product_path(@conn, :show, product.slug) %>">
                  <img src="<%= featured_image_url(product.product_images) %>" alt="<%= product.title %>" class="img-responsive" />
                </a>
              </div>

              <span class="price price-round">
                <%= readable_price(product.base_price) %>
              </span>
            </div>
          </div><!-- col md 7 -->
        <div class="<%= alternate_class_name(id, 5, 'pull') %>">
        <% else %>
        <div class="col-md-12">
        <% end %>

          <h3 class="product-title">
            <a href="<%= product_path(@conn, :show, product.slug) %>">
              <%= product.title %>
            </a>
          </h3>

          <div class="product-content">
            <p>
              <%= product.extract %>
            </p>
          </div>

          <div class="product-cta">
            <%= link to: product_path(@conn, :show, product.slug), class: "btn btn-cta" do %>
              <%= if product.base_price == 0 do %>
                Preview & Download &rarr;
              <% else %>
                Preview & Purchase &rarr;
              <% end %>
            <% end %>
          </div>
        </div><!-- col md 5 -->
      </div>

    </div>
    <% end %>
  </div><!-- products-container -->
<% else %>
<div class="coming-soon-box">
  <span class="main-icon glyphicon glyphicon-gift"></span>
  <h3>
    Coming soon.
  </h3>
  <p>
    We are working aggresively to add more resources to our collection.
  </p>
</div>
<% end %>

web/templates/product/show.html.eex
<section class="product-show">
  <div class="row">
    <div class="col-md-12">
      <div class="page-header">
        <h1 class="product-title">
          <%= @product.title %>
        </h1>
      </div><!-- product header -->
    </div>
  </div>

  <div class="row">
    <div class="col-lg-9">

      <div class="product-images">
        <%= if @product.product_images != [] do %>
          <div class="browser">
            <div class="browser-header">
              <span class="button"></span>
              <span class="button"></span>
              <span class="button"></span>
            </div>

            <div data-slick='{"slidesToShow": 1, "slidesToScroll": 1, "dots": true, "arrows": true, "respondTo": "window", "adaptiveHeight": true}'>
              <%= for image <- @product.product_images do %>
                <div class="item">
                  <img src="<%= image.secure_url %>" alt="" class="img-responsive" />
                </div>
              <% end %>
            </div>

          </div><!-- browser -->

        <% end %>
      </div><!-- product images -->


      <div class="product-content">
        <%= raw @product.content %>
      </div><!-- product-content -->


      <div class="product-categories-list">
        <h5 class="text-muted">
          Categorized under:
          <%= for cat <- @product.product_categories do %>
            <%= link cat.title, to: product_category_path(@conn, :show, cat.slug) %>
          <% end %>
        </h5>
      </div>

    </div><!-- col md 9 -->

    <div class="col-lg-3 product-sidebar">
      <div class="widget widget-secondary" data-sticky>
        <div class="widget-content">
          <%= link to: product_preview_path(@conn, :show, @product.slug), class: "btn btn-default demo-btn btn-block btn-lg", target: "_blank" do %>
            Live Preview <span class="glyphicon glyphicon-chevron-right"></span>
          <% end %>

          <table class="table variant-chooser js-variant-chooser">
            <%= for {variant, id} <- Enum.with_index @product.variants do %>
            <%= if id == 0 do %>
            <tr data-price="<%= readable_price([variant]) %>" data-purchase-url="<%= variant.purchase_url %>" class="active">
            <% else  %>
            <tr data-price="<%= readable_price([variant]) %>" data-purchase-url="<%= variant.purchase_url %>">
            <% end %>
              <td width="50px" class="variant-price">
                $<%= variant.price %>
              </td>

              <td class="variant-content">
                <h5><%= variant.title %></h5>
                <small>
                  <%= variant.description %>
                </small>
              </td>
            </tr>
            <% end %>
          </table>

          <div class="js-purchase-btn-container">
            <a href="<%= default_purchase_url(@product.variants) %>" class="btn btn-block btn-lg btn-primary purchase-btn js-purchase-btn" data-gumroad-single-product="true">
              Buy Now <span><%= readable_price(@product.variants) %></span>
            </a>
          </div>


        </div>
      </div>
    </div>
  </div>



</section>