web/router.ex
defmodule Ap.Router do
  use Ap.Web, :router
  use Plug.ErrorHandler
  use Sentry.Plug

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers

  end

  pipeline :admin do
    plug :put_layout, {Ap.LayoutView, :admin}
    plug Ap.Plugs.Authenticate
  end


  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :default_assigns do
    plug Ap.Plugs.DefaultAssigns
  end

  if Mix.env == :dev do
    forward "/sent_emails", Bamboo.EmailPreviewPlug
  end


  scope "/admin", Ap.Admin, as: :admin do
    pipe_through [:browser, :admin]

    get "/", DashboardController, :index
    resources "/users", UserController, only: [:edit, :update]

    # Blog posts
    get "/posts/drafts", PostController, :drafts
    get "/posts/published", PostController, :published
    resources "/posts", PostController
    resources "/post-categories", PostCategoryController

    # Products
    resources "/products", ProductController do
      resources "/images", ProductImageController, only: [:new, :create, :delete], as: :image
    end
    resources "/product-categories", ProductCategoryController

    resources "/pages", PageController

    # Image management from WYSIWYG editor
    post "/editor-image-upload", EditorImageUploadController, :create
    delete "/editor-image-upload", EditorImageUploadController, :delete

    resources "/support-messages", SupportMessageController, only: [:index, :show, :delete]
  end

  scope "/", Ap do
    pipe_through [:browser, :default_assigns]

    get "/", HomeController, :index
    resources "/sessions", SessionController, only: [:new, :create, :delete]

    # Newsletter
    get "/newsletter-subscribe", NewsletterSubscribeController, :index

    # Support requests
    resources "/contact", SupportMessageController, only: [:new, :create]

    # Blog
    get "/blog/categories/:slug", PostCategoryController, :show
    get "/blog/archives", PostArchiveController, :index
    resources "/blog", PostController, only: [:index, :show]

    # Static Pages
    get "/pages/:slug", PageController, :show

    # Products
    get "/preview/:slug", ProductPreviewController, :show
    get "/products/:slug", ProductCategoryController, :show
    get "/product/:slug", ProductController, :show
  end


  # Other scopes may use custom stacks.
  # scope "/api", Ap do
  #   pipe_through :api
  # end
end

web/views/admin/shared_view.ex
defmodule Ap.Admin.SharedView do
  use Ap.Web, :view
end

web/views/shared_view.ex
defmodule Ap.SharedView do
  use Ap.Web, :view
end

web/templates/shared/blog_sidebar.html.eex
<aside class="blog-sidebar">
  <div class="widget widget-secondary subscribe-widget" data-sticky>
    <h3 class="widget-title text-center">
      Subscribe
      <span>and get a <em>free</em> Bootstrap template</span>
    </h3>

    <p>
      Join our 125+ subscriber strong community to get access to exclusive free resources, regular updates to our themes, tips, deals and lots more.
    </p>

    <form action="//authenticpixels.us14.list-manage.com/subscribe/post?u=32a81f969627f2c976efef542&amp;id=b2bb29422d" method="post" target="_blank">

      <div class="form-group">
        <input placeholder="Enter your email" type="email" name="EMAIL" class="form-control">
      </div>

      <input type="submit" value="Subscribe" class="btn btn-primary">

    </form>

    <p class="meta">
      <small>
        Your email will be used to get you a weekly newsletter. Don't worry, we hate spam too.
      </small>
    </p>
  </div>
</aside>

web/templates/shared/footer.html.eex
<footer class="main-footer">
  <p>
    &copy; 2016 Authentic Pixels. All Rights Reserved.
    <%= if Ap.LayoutView.is_current_path?(@conn, "/") do %>
      <br>
      <small>
        From the makers of <a href="https://www.resumonk.com" title="Online Resume (CV) Builder" target="_blank">Resumonk</a>.
      </small>
    <% end %>
  </p>
</footer>

web/templates/shared/footer_subscribe_widget.html.eex
<div class="footer-subscribe-widget">
  <div class="widget-inner">
    <div class="row">
      <div class="col-md-12">

        <div class="widget-header">
          <h3>Subscribe to our newsletter</h3>
          <p>
            get exclusive freebies, regular updates to our templates & get notified of new template launches
          </p>
        </div>

        <div class="widget-content">
          <form action="//authenticpixels.us14.list-manage.com/subscribe/post?u=32a81f969627f2c976efef542&amp;id=b2bb29422d" method="post" target="_blank">
            <div class="input-group input-group-lg">
              <input type="email" name="EMAIL" class="form-control text-input" placeholder="Your email address">
              <span class="input-group-btn">
                <button type="submit" class="btn btn-dark">Subscribe Now</button>
              </span>
            </div><!-- /input-group -->
          </form>

          <p class="text-muted subscribe-meta">
            <small>
              We will only send you one email every Monday. Don't worry, we hate spam too.
            </small>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

web/templates/shared/header.html.eex
<header class="main-header">
  <div class="text-center">
    <a href="/" title="Authentic Pixels - Free & Premium Web Resources">
      <div id="logo">
        Authentic Pixels
      </div>

      <p class="description">
        Free & Premium Web Resources
      </p>
    </a>
  </div>
</header>

<nav class="navbar navbar-default main-navbar">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <span class="navbar-text show-for-collapsed">Free & Premium Web Resources</span>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= Ap.LayoutView.active_class(@conn, "/") %>">
          <a href="/">Home</a>
        </li>

        <%= for {title, slug} <- @product_categories do %>
          <li class="<%= Ap.LayoutView.active_class(@conn, product_category_path(@conn, :show, slug)) %>">
            <%= link title, to: product_category_path(@conn, :show, slug) %>
          </li>
        <% end %>

        <li class="<%= Ap.LayoutView.active_class(@conn, support_message_path(@conn, :new)) %>">
          <a href="<%= support_message_path(@conn, :new) %>">Contact & Support</a>
        </li>

        <li class="<%= Ap.LayoutView.active_class(@conn, post_path(@conn, :index)) %>">
          <a href="/blog">Blog</a>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <span class="show-for-collapsed">
              Pages <span class="caret"></span>
            </span>

            <span class="show-for-uncollapsed">
              <span class="more-menu-item glyphicon glyphicon-option-horizontal"></span>
            </span>
          </a>
          <ul class="dropdown-menu">
            <li><a href="<%= page_path(@conn, :show, "about") %>">About</a></li>
            <li><a href="<%= page_path(@conn, :show, "privacy") %>">Privacy</a></li>
            <li><a href="<%= page_path(@conn, :show, "terms") %>">Terms</a></li>
          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li class="btn-container">
          <a class="newsletter-btn" href="/newsletter-subscribe">
            <span>
              Subscribe for freebies &rarr;
            </span>
          </a>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>